# This is a daily.dev - devcard workflow

name: DevCard

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 0 * * *"



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.2.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          # Commit message
          commit_message: main is Update ${filename}
